name: EnchantmentSlots
version: '${project.version}'
main: cn.superiormc.enchantmentslots.EnchantmentSlots
api-version: 1.14
softdepend:
  - EcoEnchants
  - ExcellentEnchants
  - EcoItems
  - EcoArmor
  - MythicMobs
  - MMOItems
  - NeigeItems
  - ItemsAdder
  - Oraxen
  - ProtocolLib
  - eco
  - EnchantGui
commands:
  enchantmentslots:
    aliases:
      - "es"
    usage: "/enchantmentslots"
    description: "EnchantmentSlots Main Command."