name: EnchantmentSlots
version: '${project.version}'
main: cn.superiormc.enchantmentslots.EnchantmentSlots
api-version: 1.14
folia-supported: true
softdepend:
  - EcoEnchants
  - ExcellentEnchants
  - Aiyatsbus
  - EcoItems
  - EcoArmor
  - MythicMobs
  - MMOItems
  - NeigeItems
  - ItemsAdder
  - Oraxen
  - packetevents
  - eco
  - NBTAPI
  - CraftEngine
  - EnchantGui
  - ExecutableItems
  - InteractiveChat
  - TrChat
  - QuickShop-Hikari
commands:
  enchantmentslots:
    aliases:
      - "es"
    usage: "/enchantmentslots"
    description: "EnchantmentSlots Main Command."